# Generated by Django 5.2.8 on 2025-12-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_source', models.CharField(default='ProfitAdvisor_Chatbot', max_length=100)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('third_party_apps', models.JSONField(blank=True, default=list, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('aov', models.FloatField(blank=True, null=True)),
                ('monthly_orders', models.IntegerField(blank=True, null=True)),
                ('commission_rate', models.FloatField(blank=True, null=True)),
                ('monthly_fixed_fee', models.FloatField(blank=True, null=True)),
                ('calculated_annual_leak', models.FloatField(blank=True, null=True)),
                ('estimated_recovery', models.FloatField(blank=True, null=True)),
                ('lead_score_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
