# Generated by Django 5.2.8 on 2025-12-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
