# Generated by Django 5.2.8 on 2025-12-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_lead_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='consultation_requested',
            field=models.BooleanField(default=False),
        ),
    ]
